### ISSUE TITLE
Use tests from upstream

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pydata-sphinx-theme-feedstock#19]
With this in, we should be able to use the as-distributed tests: https://github.com/pydata/pydata-sphinx-theme/pull/457

**Comment by bollwyvl** [comment]
They were taken back out, not going to bother too much arguing to get them back.

**Comment by jorisvandenbossche** [comment]
Ah, that might have been an unintended side effect of the sphinx-theme-builder migration

**Comment by jorisvandenbossche** [comment]
Actually, from checking the latest sdist for 0.8.0, the tests are still included in the sdist

**Comment by bollwyvl** [comment]
mmmm... perhaps, but the complexity/specialness of the post-0.8.0 build chain, the sdist of not much value in a conda (or any downstream) setting. All the new python build backends, and keeping on top of their seeming-weekly-changing compatibility profiles, are becoming a fairly significant, and only minimally rewarding, chore.
